// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwhu0Rn1lXIU1FLraNPLdu7oVd2u3oUdo',
    appId: '1:633590187282:web:b3fe2fdcd4dae618b39fcb',
    messagingSenderId: '633590187282',
    projectId: 'tip-akademi-764ac',
    authDomain: 'tip-akademi-764ac.firebaseapp.com',
    storageBucket: 'tip-akademi-764ac.firebasestorage.app',
    measurementId: 'G-BVXW0S4CXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOLvGgnANRyLWgHOlKIQ3KpdqY5zBQSlM',
    appId: '1:633590187282:android:2093b60f276436f5b39fcb',
    messagingSenderId: '633590187282',
    projectId: 'tip-akademi-764ac',
    storageBucket: 'tip-akademi-764ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtgE1XpmIe07scky8DvXVdsK-1uqrRLlc',
    appId: '1:633590187282:ios:3b62c83a4075bc3bb39fcb',
    messagingSenderId: '633590187282',
    projectId: 'tip-akademi-764ac',
    storageBucket: 'tip-akademi-764ac.firebasestorage.app',
    iosBundleId: 'com.kiraathanelabs.tipakademi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtgE1XpmIe07scky8DvXVdsK-1uqrRLlc',
    appId: '1:633590187282:ios:3b62c83a4075bc3bb39fcb',
    messagingSenderId: '633590187282',
    projectId: 'tip-akademi-764ac',
    storageBucket: 'tip-akademi-764ac.firebasestorage.app',
    iosBundleId: 'com.kiraathanelabs.tipakademi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwhu0Rn1lXIU1FLraNPLdu7oVd2u3oUdo',
    appId: '1:633590187282:web:9c5b6d9d820877f5b39fcb',
    messagingSenderId: '633590187282',
    projectId: 'tip-akademi-764ac',
    authDomain: 'tip-akademi-764ac.firebaseapp.com',
    storageBucket: 'tip-akademi-764ac.firebasestorage.app',
    measurementId: 'G-XJN066MLYB',
  );
}
