// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:913268485080:web:727fe30d3c02eac70ae0ad',
    messagingSenderId: '913268485080',
    projectId: 'enneagram-8b860',
    authDomain: 'enneagram-8b860.firebaseapp.com',
    storageBucket: 'enneagram-8b860.firebasestorage.app',
    measurementId: 'G-RQQ97P3M8M',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:913268485080:android:1dded51205fe0ba20ae0ad',
    messagingSenderId: '913268485080',
    projectId: 'enneagram-8b860',
    storageBucket: 'enneagram-8b860.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:913268485080:ios:2680f6dddc68de2b0ae0ad',
    messagingSenderId: '913268485080',
    projectId: 'enneagram-8b860',
    storageBucket: 'enneagram-8b860.firebasestorage.app',
    iosBundleId: 'com.kiraathanelabs.enneagram',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:913268485080:ios:2680f6dddc68de2b0ae0ad',
    messagingSenderId: '913268485080',
    projectId: 'enneagram-8b860',
    storageBucket: 'enneagram-8b860.firebasestorage.app',
    iosBundleId: 'com.kiraathanelabs.enneagram',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:913268485080:web:95da348290e2d48f0ae0ad',
    messagingSenderId: '913268485080',
    projectId: 'enneagram-8b860',
    authDomain: 'enneagram-8b860.firebaseapp.com',
    storageBucket: 'enneagram-8b860.firebasestorage.app',
    measurementId: 'G-EW1N6CBN9X',
  );
}
